---
# Copyright (C) 2021-2024 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Ensure filesystems
  community.general.filesystem:
    dev: "/dev/{{ item.0.vgname }}/{{ item.1.lvname }}"
    fstype: "{{ item.1.fs.type }}"
    opts: "{{ item.1.fs.opts | default(omit) }}"
    state: "{{ item.1.fs.state }}"
  loop: "{{ q('subelements', lvm_vgs, 'lvm_lvs', {'skip_missing': True}) }}"
  loop_control:
    label: >
           "DEV: /dev/{{ item.0.vgname }}/{{ item.1.lvname }} |
            FSTYPE: {{ item.1.fs.type | default('not defined') }}"
  when:
    - item.1.fs is defined
    - item.1.fs.state == "present"
  tags:
    - lvm-ensure-filesystems
